# Pandas

Pandas kütüphanesi veriyi analiz etmek için kullanılır. Veri bilimi projelerinde,veri okuma, veri ön işleme gibi adımlarda kullanılır.
Pandasta en çok kullanılan veri yapılar Series ve DataFrame yapılarıdır.

**Seriler**

Seriler bir tablodaki sütunlar gibidir. Bir boyutlu arraylerdir.

In [1]:
import pandas as pd

In [2]:
seri = pd.Series([12,47,34,66,50])
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [3]:
type(seri)

pandas.core.series.Series

In [4]:
#index bilgisi verir
seri.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
#serideki eleman sayısını verir
seri.size

5

In [6]:
#boyut bilgisi verir
seri.ndim

1

In [7]:
#değerlere array formunda  erişmek istersek values methodunu kullanabiliriz
seri.values

array([12, 47, 34, 66, 50], dtype=int64)

In [10]:
#fonksiyonun içine girilen değer kadar veriyi gösterir
seri.head(3)

0    12
1    47
2    34
dtype: int64

In [11]:
seri.tail(3)

2    34
3    66
4    50
dtype: int64

In [12]:
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [13]:
#serilerde de indexing ve slicing işlemlerini yapabiliyoruz
seri[0]

12

In [14]:
seri[2]

34

In [15]:
seri[3]

66

In [16]:
seri[0:2]

0    12
1    47
dtype: int64

In [17]:
seri[1:4]

1    47
2    34
3    66
dtype: int64

In [18]:
#indexleri değiştirebilir,isimlendirme yapabiliriz
seri2 = pd.Series([15,45,63,85,41],index=[1,8,5,3,6])
seri2

1    15
8    45
5    63
3    85
6    41
dtype: int64

In [19]:
seri2[1]

15

In [20]:
seri2[5]

63

In [21]:
seri3 = pd.Series([15,45,63,85,41],index=["a","b","c","d","e"])
seri3

a    15
b    45
c    63
d    85
e    41
dtype: int64

In [22]:
seri3.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [23]:
seri3["b"]

45

In [24]:
seri3["d"]

85

In [25]:
seri3["a":"d"]

a    15
b    45
c    63
d    85
dtype: int64

In [26]:
#sözlük üzerinden seri oluşturalım
sozluk = {"Ayşe":42,
          "Elif":27,
          "Fatma":36}
sozluk

{'Ayşe': 42, 'Elif': 27, 'Fatma': 36}

In [27]:
yeni_sozluk = pd.Series(sozluk)
yeni_sozluk

Ayşe     42
Elif     27
Fatma    36
dtype: int64

In [28]:
yeni_sozluk["Ayşe"]

42

In [31]:
#######################
import numpy as np
dizi = np.random.randint(50,size=6)
dizi

array([13,  2, 42, 13, 28, 26])

In [32]:
seri2 = pd.Series(dizi)
seri2

0    13
1     2
2    42
3    13
4    28
5    26
dtype: int32

In [33]:
seri2.index = ["a","b","c","d","e","f"]

In [34]:
seri2

a    13
b     2
c    42
d    13
e    28
f    26
dtype: int32

In [35]:
seri2["a":"d"]

a    13
b     2
c    42
d    13
dtype: int32

In [36]:
seri2[["b","d"]]

b     2
d    13
dtype: int32

In [37]:
seri2[["a","c","f"]]

a    13
c    42
f    26
dtype: int32

In [40]:
seri2[["b","d"]]=55
seri2

a    13
b    55
c    42
d    55
e    28
f    26
dtype: int32

**DataFrame**

In [41]:
pd.DataFrame(seri2)

0
a  13
b  55
c  42
d  55
e  28
f  26

In [42]:
pd.DataFrame(seri2,columns=["Sayılar"])

Sayılar
a       13
b       55
c       42
d       55
e       28
f       26

In [44]:
yeni_dizi=np.random.randint(25,size=12).reshape(4,3)
yeni_dizi

array([[22, 21,  0],
       [16,  9, 19],
       [22, 15,  2],
       [22,  8, 24]])

In [45]:
df = pd.DataFrame(yeni_dizi,columns=["col1","col2","col3"])
df

col1  col2  col3
0    22    21     0
1    16     9    19
2    22    15     2
3    22     8    24

In [46]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [47]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [48]:
df.columns=["1.Sütun","2.Sütun","3.Sütun"]
df

1.Sütun  2.Sütun  3.Sütun
0       22       21        0
1       16        9       19
2       22       15        2
3       22        8       24

In [49]:
#satır ve sütun bilgisi verir
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['1.Sütun', '2.Sütun', '3.Sütun'], dtype='object')]

In [50]:
df.ndim

2

In [51]:
df.shape

(4, 3)

In [52]:
df.values

array([[22, 21,  0],
       [16,  9, 19],
       [22, 15,  2],
       [22,  8, 24]])

In [53]:
#Bir sözlükten DataFrame oluşturalım
a = np.random.randint(10,size=5)
b = np.random.randint(10,size=5)
c = np.random.randint(10,size=5)
print(a)
print(b)
print(c)

[7 4 1 4 3]
[0 8 8 6 4]
[7 0 4 6 1]


In [ ]:
{"a":5,"b":5}

In [54]:
sozluk2 = {"Col1":a,"Col2":b,"Col3":c}
sozluk2

{'Col1': array([7, 4, 1, 4, 3]),
 'Col2': array([0, 8, 8, 6, 4]),
 'Col3': array([7, 0, 4, 6, 1])}

In [55]:
data = pd.DataFrame(sozluk2)
data

Col1  Col2  Col3
0     7     0     7
1     4     8     0
2     1     8     4
3     4     6     6
4     3     4     1

In [56]:
data[0:3]

Col1  Col2  Col3
0     7     0     7
1     4     8     0
2     1     8     4

In [57]:
data[1:-1]

Col1  Col2  Col3
1     4     8     0
2     1     8     4
3     4     6     6

In [58]:
data[::2]

Col1  Col2  Col3
0     7     0     7
2     1     8     4
4     3     4     1

In [59]:
data[1:4][["Col1","Col3"]]

Col1  Col3
1     4     0
2     1     4
3     4     6

In [60]:
data[0:3]["Col2"]

0    0
1    8
2    8
Name: Col2, dtype: int32

In [61]:
data[0:3][["Col2"]]

Col2
0     0
1     8
2     8

In [62]:
data[["Col1","Col3"]]

Col1  Col3
0     7     7
1     4     0
2     1     4
3     4     6
4     3     1

In [63]:
data[["Col2"]]

Col2
0     0
1     8
2     8
3     6
4     4

In [64]:
data

Col1  Col2  Col3
0     7     0     7
1     4     8     0
2     1     8     4
3     4     6     6
4     3     4     1

In [ ]:
#Silme işlemi için drop kullanılır.
data

In [65]:
data.drop(1,axis=0)

Col1  Col2  Col3
0     7     0     7
2     1     8     4
3     4     6     6
4     3     4     1

In [66]:
data

Col1  Col2  Col3
0     7     0     7
1     4     8     0
2     1     8     4
3     4     6     6
4     3     4     1

In [67]:
#İşlemin kalıcı olması için inplace True yapılmalı
data.drop(1,axis=0,inplace=True)

In [68]:
data

Col1  Col2  Col3
0     7     0     7
2     1     8     4
3     4     6     6
4     3     4     1

In [69]:
new_data = data.drop("Col2",axis=1)
new_data

Col1  Col3
0     7     7
2     1     4
3     4     6
4     3     1

In [70]:
data

Col1  Col2  Col3
0     7     0     7
2     1     8     4
3     4     6     6
4     3     4     1

In [71]:
#Yeni bir sütun eklemek
data["Col4"] = data["Col1"]/data["Col2"]
data

Col1  Col2  Col3      Col4
0     7     0     7       inf
2     1     8     4  0.125000
3     4     6     6  0.666667
4     3     4     1  0.750000

In [72]:
seri2

a    13
b    55
c    42
d    55
e    28
f    26
dtype: int32

In [73]:
data2=pd.DataFrame(seri2)
data2

0
a  13
b  55
c  42
d  55
e  28
f  26

**Değişken Seçimi: loc & iloc**

**loc:** Etikete dayalı seçme işlemi gerçekleştirir. Seçmek istediğimiz satır ve sütunun adını belirtmek gerekir. Seçimlerde verilen aralığın son elemanını içerir.

[satır_adı,sütun_adı]

**iloc:** İndexe dayalı seçme işlemidir. Seçmek istenilen satur ve sütunun indexi belirtilir. Indexe dayalı bir yöntem olduğundan belirtilen aralığın son öğesini içermez.

[satır_indexi,sütun_indexi]

In [75]:
numbers = np.random.randint(40,size=(10,3))
numbers

array([[16, 31, 11],
       [18, 36, 32],
       [25,  2,  8],
       [32,  3,  7],
       [16,  5,  3],
       [21,  2,  1],
       [29, 30,  3],
       [14, 18,  4],
       [29, 36,  2],
       [35, 24, 15]])

In [76]:
df = pd.DataFrame(numbers,columns=["Col1","Col2","Col3"])
df

Col1  Col2  Col3
0    16    31    11
1    18    36    32
2    25     2     8
3    32     3     7
4    16     5     3
5    21     2     1
6    29    30     3
7    14    18     4
8    29    36     2
9    35    24    15

In [78]:
df.loc[0,"Col3"]

11

In [79]:
df.iloc[0,2]

11

In [80]:
df.loc[6,"Col2"]

30

In [81]:
df.iloc[6,1]

30

In [82]:
df.loc[2:8,"Col2":"Col3"]

Col2  Col3
2     2     8
3     3     7
4     5     3
5     2     1
6    30     3
7    18     4
8    36     2

In [83]:
df

Col1  Col2  Col3
0    16    31    11
1    18    36    32
2    25     2     8
3    32     3     7
4    16     5     3
5    21     2     1
6    29    30     3
7    14    18     4
8    29    36     2
9    35    24    15

In [84]:
df.iloc[2:9,1:3]

Col2  Col3
2     2     8
3     3     7
4     5     3
5     2     1
6    30     3
7    18     4
8    36     2

In [88]:
df.loc[0:5]

Col1  Col2  Col3
0    16    31    11
1    18    36    32
2    25     2     8
3    32     3     7
4    16     5     3
5    21     2     1

In [90]:
df.iloc[2:7]

Col1  Col2  Col3
2    25     2     8
3    32     3     7
4    16     5     3
5    21     2     1
6    29    30     3

In [91]:
df.loc[2:7,"Col2"]

2     2
3     3
4     5
5     2
6    30
7    18
Name: Col2, dtype: int32

In [92]:
df.loc[2:7][["Col2"]]

Col2
2     2
3     3
4     5
5     2
6    30
7    18

In [ ]:
#########

In [93]:
df

Col1  Col2  Col3
0    16    31    11
1    18    36    32
2    25     2     8
3    32     3     7
4    16     5     3
5    21     2     1
6    29    30     3
7    14    18     4
8    29    36     2
9    35    24    15

In [94]:
df["Col1"]>20

0    False
1    False
2     True
3     True
4    False
5     True
6     True
7    False
8     True
9     True
Name: Col1, dtype: bool

In [95]:
df[df["Col1"]>20]

Col1  Col2  Col3
2    25     2     8
3    32     3     7
5    21     2     1
6    29    30     3
8    29    36     2
9    35    24    15

In [96]:
df[df["Col1"]>20][["Col1"]]

Col1
2    25
3    32
5    21
6    29
8    29
9    35

In [97]:
df[df["Col3"]<30]

Col1  Col2  Col3
0    16    31    11
2    25     2     8
3    32     3     7
4    16     5     3
5    21     2     1
6    29    30     3
7    14    18     4
8    29    36     2
9    35    24    15

In [98]:
df[df["Col3"]<30][["Col3"]]

Col3
0    11
2     8
3     7
4     3
5     1
6     3
7     4
8     2
9    15

In [99]:
df[df["Col3"]<30][["Col2","Col3"]]

Col2  Col3
0    31    11
2     2     8
3     3     7
4     5     3
5     2     1
6    30     3
7    18     4
8    36     2
9    24    15

In [100]:
df[(df["Col2"]>20) & (df["Col3"]<30)]

Col1  Col2  Col3
0    16    31    11
6    29    30     3
8    29    36     2
9    35    24    15

In [101]:
#join ile birleştirme işlemi yapılır
df

Col1  Col2  Col3
0    16    31    11
1    18    36    32
2    25     2     8
3    32     3     7
4    16     5     3
5    21     2     1
6    29    30     3
7    14    18     4
8    29    36     2
9    35    24    15

In [102]:
df2 = df+50
df2

Col1  Col2  Col3
0    66    81    61
1    68    86    82
2    75    52    58
3    82    53    57
4    66    55    53
5    71    52    51
6    79    80    53
7    64    68    54
8    79    86    52
9    85    74    65

In [103]:
pd.concat([df,df2])

Col1  Col2  Col3
0    16    31    11
1    18    36    32
2    25     2     8
3    32     3     7
4    16     5     3
5    21     2     1
6    29    30     3
7    14    18     4
8    29    36     2
9    35    24    15
0    66    81    61
1    68    86    82
2    75    52    58
3    82    53    57
4    66    55    53
5    71    52    51
6    79    80    53
7    64    68    54
8    79    86    52
9    85    74    65

In [104]:
pd.concat([df,df2],ignore_index=True)

Col1  Col2  Col3
0     16    31    11
1     18    36    32
2     25     2     8
3     32     3     7
4     16     5     3
5     21     2     1
6     29    30     3
7     14    18     4
8     29    36     2
9     35    24    15
10    66    81    61
11    68    86    82
12    75    52    58
13    82    53    57
14    66    55    53
15    71    52    51
16    79    80    53
17    64    68    54
18    79    86    52
19    85    74    65

In [105]:
df2.columns=["Col1","Col2","Col4"]
df2

Col1  Col2  Col4
0    66    81    61
1    68    86    82
2    75    52    58
3    82    53    57
4    66    55    53
5    71    52    51
6    79    80    53
7    64    68    54
8    79    86    52
9    85    74    65

In [106]:
pd.concat([df,df2])

Col1  Col2  Col3  Col4
0    16    31  11.0   NaN
1    18    36  32.0   NaN
2    25     2   8.0   NaN
3    32     3   7.0   NaN
4    16     5   3.0   NaN
5    21     2   1.0   NaN
6    29    30   3.0   NaN
7    14    18   4.0   NaN
8    29    36   2.0   NaN
9    35    24  15.0   NaN
0    66    81   NaN  61.0
1    68    86   NaN  82.0
2    75    52   NaN  58.0
3    82    53   NaN  57.0
4    66    55   NaN  53.0
5    71    52   NaN  51.0
6    79    80   NaN  53.0
7    64    68   NaN  54.0
8    79    86   NaN  52.0
9    85    74   NaN  65.0

In [107]:
#ikisinde de ortak olan sütunları birleştirir
pd.concat([df,df2],join="inner")

Col1  Col2
0    16    31
1    18    36
2    25     2
3    32     3
4    16     5
5    21     2
6    29    30
7    14    18
8    29    36
9    35    24
0    66    81
1    68    86
2    75    52
3    82    53
4    66    55
5    71    52
6    79    80
7    64    68
8    79    86
9    85    74

In [108]:
pd.concat([df,df2],axis=1)

Col1  Col2  Col3  Col1  Col2  Col4
0    16    31    11    66    81    61
1    18    36    32    68    86    82
2    25     2     8    75    52    58
3    32     3     7    82    53    57
4    16     5     3    66    55    53
5    21     2     1    71    52    51
6    29    30     3    79    80    53
7    14    18     4    64    68    54
8    29    36     2    79    86    52
9    35    24    15    85    74    65

In [ ]:
####################

In [109]:
data = pd.DataFrame({"Öğrenciler":["Ayşe","Mehmet","Fatma","Fatma","Mehmet","Ayşe","Ayşe","Fatma","Mehmet"],
                   "Dersler":["Matematik","Türkçe","Türkçe","Fen Bilgisi","Matematik","Fen Bilgisi","Türkçe","Matematik","Fen Bilgisi"],
                    "Puan":[80,75,92,78,64,84,73,94,90]})

data

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
1     Mehmet       Türkçe    75
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
4     Mehmet    Matematik    64
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [110]:
data2 = pd.DataFrame({"Öğretmenler":["Selin","Furkan","Emine"],
                   "Dersler":["Matematik","Türkçe","Fen Bilgisi"]})
data2

Öğretmenler      Dersler
0       Selin    Matematik
1      Furkan       Türkçe
2       Emine  Fen Bilgisi

In [111]:
pd.merge(data,data2)

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [112]:
new_data = pd.merge(data,data2,on="Dersler")
new_data

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [113]:
data["Öğrenciler"]

0      Ayşe
1    Mehmet
2     Fatma
3     Fatma
4    Mehmet
5      Ayşe
6      Ayşe
7     Fatma
8    Mehmet
Name: Öğrenciler, dtype: object

In [114]:
data[["Öğrenciler"]]

Öğrenciler
0       Ayşe
1     Mehmet
2      Fatma
3      Fatma
4     Mehmet
5       Ayşe
6       Ayşe
7      Fatma
8     Mehmet

In [115]:
data

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
1     Mehmet       Türkçe    75
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
4     Mehmet    Matematik    64
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [116]:
#Ayşenin ders ve puanına bakalım
data[data["Öğrenciler"]=="Ayşe"]

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73

In [117]:
data[data["Öğrenciler"]=="Mehmet"]

Öğrenciler      Dersler  Puan
1     Mehmet       Türkçe    75
4     Mehmet    Matematik    64
8     Mehmet  Fen Bilgisi    90

In [118]:
data[data["Öğrenciler"]=="Mehmet"][["Dersler","Puan"]]

Dersler  Puan
1       Türkçe    75
4    Matematik    64
8  Fen Bilgisi    90

In [119]:
data[data["Dersler"]=="Matematik"]

Öğrenciler    Dersler  Puan
0       Ayşe  Matematik    80
4     Mehmet  Matematik    64
7      Fatma  Matematik    94

In [120]:
data[data["Dersler"]=="Fen Bilgisi"]

Öğrenciler      Dersler  Puan
3      Fatma  Fen Bilgisi    78
5       Ayşe  Fen Bilgisi    84
8     Mehmet  Fen Bilgisi    90

In [121]:
data[data["Dersler"]=="Fen Bilgisi"][["Öğrenciler","Puan"]]

Öğrenciler  Puan
3      Fatma    78
5       Ayşe    84
8     Mehmet    90

In [122]:
data[data["Puan"]>80]

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
5       Ayşe  Fen Bilgisi    84
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [123]:
data[(data["Dersler"] =="Matematik") & (data["Puan"]>80)]

Öğrenciler    Dersler  Puan
7      Fatma  Matematik    94

In [124]:
data[(data["Dersler"] =="Türkçe") & (data["Puan"]<85)]

Öğrenciler Dersler  Puan
1     Mehmet  Türkçe    75
6       Ayşe  Türkçe    73

In [126]:
data[(data["Öğrenciler"]=="Mehmet")&(data["Dersler"]=="Fen Bilgisi")]

Öğrenciler      Dersler  Puan
8     Mehmet  Fen Bilgisi    90